# Generated by Django 5.2.8 on 2025-11-28 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_alter_assignment_student_alter_certificate_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='lesson',
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_app.country'),
        ),
    ]
