# Generated by Django 5.2.8 on 2025-11-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_remove_assignment_lesson_city_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
